// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilrzazwuyrnykwobibxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlscnphend1eXJueWt3b2JpYnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNDM1ODcsImV4cCI6MjA5MDgxOTU4N30.mKn3Z1Fx9QFDJe0I4RNjWYek-Itj9ZiG-xzWFVmPRwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});